services:
  web:
    build: .
    container_name: pri_site_app
    restart: always
    ports:
      - "8505:8000"
    volumes:
      - db_data:/app/db.sqlite3
      - ./media:/app/media
      - ./dxf_files:/app/dxf_files
    env_file:
      - .env
    command: sh -c "python manage.py migrate && gunicorn config.wsgi:application --config gunicorn.conf.py"
 
volumes:
  db_data: